### ISSUE TITLE
Missing or invalid. request() method: eth_signTypedData_v4 for Limit order

### ISSUE THREAD

**Issue by 48-mq** [cowprotocol/cowswap#4412] opened 2024-05-12 16:22 UTC
I keep getting the following error when trying to place a limit order. I've performed a transaction with this wallet before so I know WalletConnect works okay. Disconnecting and reconnecting the wallet didn't help, either.

Missing or invalid. request() method: eth_signTypedData_v4

![Screenshot 2024-05-12 at 11-41-25 CoW Swap The smartest way to trade cryptocurrencies](https://github.com/cowprotocol/cowswap/assets/145857730/e4656d66-304e-4756-846f-71ae4117cf3f)

**Comment by 48-mq** [comment] 2024-05-14 16:59
@shoom3301 @anxolin 

Any thoughts on this?

**Comment by shoom3301** [comment] 2024-05-14 18:01
@48-mq which wallet do you use?
Looks like the wallet doesn’t support typed data signing.

**Comment by 48-mq** [comment] 2024-05-14 18:07
Thanks @shoom3301 ! This was with UnstoppableWallet, I'll try with another wallet to see if that will work...

**Comment by elena-zh** [comment] 2024-05-16 14:57
Hey @48-mq , could you please provide a bit more details:
- tokens you are trying to trade, 
- chain, 
- amounts 
- order duration values? 
Also, it would be great to know whether your wallet is installed to Android or iOS device. 

Thank you in advance.

**Comment by 48-mq** [comment] 2024-05-16 15:00
@elena-zh The issue presents regardless of token, chain, amount, and order duration. Wallets I've used so far are Cake and Unstoppable (both on Android). 

Unstoppable did quickly acknowledge the issue and are rolling out a fix within a few days.

**Comment by elena-zh** [comment] 2024-05-16 15:04
@48-mq , I've checked this with Unstoppable in iOS, everything works fine. Btw, could you please clarify whether the issue is no longer relevant for you after Unstoppable fix?

**Comment by 48-mq** [comment] 2024-05-16 15:05
Sure, I'll keep this issue posted with my findings

**Comment by elena-zh** [comment] 2024-05-16 15:31
@48-mq , I checked with Cake and Unstoppable wallets in Android. The issue is still reproducible, and I should say that it is on these wallets' side. As a temporary workaround I could suggest you to try using Rabby/Metamask/imToken wallets as they support typed data signing.
For now, I'm closing the current task, but feel free to let us know if these issues are resolved.

**Closed by elena-zh** 2024-05-16 15:31 UTC
