### ISSUE TITLE
2440/uni merge: issues with WC

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#351] opened 2022-04-02 23:20 UTC
Related to #2536
1.  the 2nd QR code is not generated when Try again WC connection process
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a50d30f5-e2d2-406a-9650-74c5e6c8265f)
2. When connected to WC (using 'Copy link'), wallet info is not displayed in the activity modal
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2e2b59f5-6695-4478-94ea-2796fc95fccb)

> Original issue https://github.com/gnosis/cowswap/issues/2641 by @elena-zh

**Comment by nenadV91** [comment] 2022-04-08 11:16
This issue is probably related to https://github.com/gnosis/cowswap/issues/1929 and this should be fixed in here https://github.com/cowprotocol/cowswap/pull/360

**Comment by elena-zh** [comment] 2022-04-08 11:22
@nenadV91 , the issue is related exactly to the Uni merge PR. 
I assume that code in #360 does not contain changes related to #374 PR

**Comment by nenadV91** [comment] 2022-04-08 12:37
I think it does because this UNI merge updates the `@web3-react/walletconnect-connector` version which is the same thing I did in that PR and that this issue happens, but its fixed in that #360  PR

**Comment by anxolin** [comment] 2022-04-22 10:00
But then, after Nenas fix, it should be OK. So probably is best to rebase, retest and review https://github.com/cowprotocol/cowswap/pull/360

**Comment by elena-zh** [comment] 2022-04-22 12:11
Only the last part of the issue is fixed in this PR (case 1)
Case 2 is still reproducible here
![safe](https://user-images.githubusercontent.com/70885163/164711785-ae7a9a12-9e98-42ba-8c0c-0ef8262fbfd6.jpg)

**Comment by alfetopito** [comment] 2022-04-22 15:36
Seems to be caused by the same issue as https://github.com/cowprotocol/cowswap/issues/342

**Closed** 2022-05-04 12:10 UTC
Labels: app:CowSwap, Bug, Medium
