### ISSUE TITLE
Issues related to refactoring PR#1041

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/cowswap#1057] opened 2022-09-08 14:12 UTC
Related to #1041

1. [Swap and New Swap]: Insufficient balance error is displayed when ETH/WETH token pair is selected, user is not connected. 
**Expected**: 'Connect Wallet' button should be displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/69b4b12a-0c8e-492f-9e70-d1ecb8876804)

2. [New Swap]: Token pair is displayed in the form by default when open the app (the feature was removed in the v.1.21). Moreover, it is different one in GC that on other networks
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b250b17b-925e-4b1c-907c-d6298d7a499b)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6accb0cc-6d26-4fbf-85af-ab5405e1629e)

3. Maybe not an issue, but when an error is displayed on the New swap page, the same error is displayed for the Swap page, however, it might be irrelevant
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1356a478-c505-405c-988b-75f07db1505d)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bc722e8e-f45d-4643-9126-c5c3e8bf8e6f)

4.  [Swap and New Swap] Unwrap/wrap button does not work (not always reproducible though)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/711e8aa0-c5c9-4da6-9d26-74d477067d0f)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/800328ba-0f3e-46b1-9659-b63a332ea7d0)

5. I see Quotes requests in the console when I select eth/weth token pair (should not appear)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/24fb977f-7644-4125-af58-8668d10591d2)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3d162cc6-7d83-4699-a0eb-d24e07ffeb35)

6. Tons of 'quotes' requests in Console (network tab) when Tokens page is opened
![image](https://user-images.githubusercontent.com/70885163/189145512-65f1b577-c665-476a-9a92-04057d9ed6b8.png)

7. I can't cancel an order. Possible reason: I was connected to GSafe wallet before 
![can't cancel an order](https://user-images.githubusercontent.com/70885163/189149069-a8b5d5d9-4479-403d-8ab8-8582eba8f2cd.jpg)

8. Price impact is not displayed on the field: Go to gorli, select WETH-USDC token pair, compare with Dev environment
![image](https://user-images.githubusercontent.com/70885163/189150657-8653d8b8-1e87-403c-9113-1b1f35debbc5.png)
![dev](https://user-images.githubusercontent.com/70885163/189150688-73bad33f-2e6f-4dd4-be9b-ffa4f8c34e7f.jpg)

**Additional context:** when a price impact is not displayed (not possible to calculate it), the banner should appear on the Swap form. It should have a checkbox that keeps Swap button disabled in [regular ](https://cowprotocol.testrail.io/index.php?/cases/view/434) mode, and a view mode in [Expert ](https://cowprotocol.testrail.io/index.php?/cases/view/435)mode 
![image](https://user-images.githubusercontent.com/70885163/189151039-bdee99f1-729e-484b-b686-a0632573f083.png)
Additionally, the banner should appear on confirmation modal for regular mode. 

9. I have got a frozen disabled Swap button after a token approval 
![image](https://user-images.githubusercontent.com/70885163/189162425-b2dd9d61-96ba-4309-bf0b-5695e520b62e.png)

**Comment by shoom3301** [comment] 2022-09-09 08:09
1. https://github.com/cowprotocol/cowswap/pull/1049/commits/c6c5692a41a2b7fedb0f602089840b1c520effac
2. https://github.com/cowprotocol/cowswap/pull/1049/commits/7f6ce141e8b7a0b9de4209686cda4543f26bb44b. Warning: after this fix, output currency won't be set by default. However, if you set it manually after the next page reload it will be restored
3. Yes, this is irrelevant, and this situation will not happen after we replace the old swap with a new one
4. Can't reproduce
5. Should be fixed in the other task
6. Should be fixed in the other task
7. Can't reproduce
8. Can't reproduce :(

**Comment by elena-zh** [comment] 2022-09-09 14:02
Hey @shoom3301 , here are steps to reproduce the 4th case: 
1. Connect to MM
2. Connect to a Safe wallet (using Change wallet button)
3. Place an order in Safe, wait till it is executed
4. Change a wallet back to MM
5. Try wrap/unwrap a token there

I was not able to. See the video: https://watch.screencastify.com/v/S8jUpo3yyCHU8foiVXKG

**Comment by elena-zh** [comment] 2022-09-09 14:37
I have not been able to reproduce again case 9, but when I was recording the issue I was able to catch case 8: I selected another toke pair, now UNI-DAI in Rinkeby, and did not get a price impact calculated
![image](https://user-images.githubusercontent.com/70885163/189372657-ebc46d0d-9cdb-46bd-9897-360470ef437f.png)
And there was no price impact banner on the swap form

> **Additional context:** when a price impact is not displayed (not possible to calculate it), the banner should appear on the Swap form. It should have a checkbox that keeps Swap button disabled in [regular ](https://cowprotocol.testrail.io/index.php?/cases/view/434) mode, and a view mode in [Expert ](https://cowprotocol.testrail.io/index.php?/cases/view/435)mode 
> ![image](https://user-images.githubusercontent.com/70885163/189151039-bdee99f1-729e-484b-b686-a0632573f083.png)
> Additionally, the banner should appear on confirmation modal for regular mode. 
This is how it should look like: 
![image](https://user-images.githubusercontent.com/70885163/189375418-b078dab0-2b33-460d-949c-cf3a0608e8e9.png)

**Comment by elena-zh** [comment] 2022-09-09 15:30
And I can't reproduce case 7 today. 
I will keep my eye on it though.

**Closed** 2022-09-19 13:10 UTC
Labels: app:CowSwap, Bug, WebSquad
