### ISSUE TITLE
Change state to wrapping/unwrapping when request is sent to wallet

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#187] opened 2022-04-02 22:11 UTC
Not a priority, but it would be nice to add a 'Wrap'/'Unwrap' buttons' state as 'wrapping'/'unwrapping' when a transaction is sent to a connected wallet. Besides, it would be nice to disable them for this state.
Currently, buttons are enabled, and a user may click a lot of times on them creating a lot of transaction requests in the connected wallet.
![wrapping1.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d87f9a6a-02bd-47f0-9fdf-1250c2b0d86d)

-----------------------------------------------------

New behavior introduced in #3786 also still contains this issue: 
Wrapping/Unnwrapping/Approve states: a user can press on the back button while a TX is pending, so the button will be clickable again (and it is not in the Pending state)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/3cbd16a9-d248-4131-b4d4-013bd43695e7)
![image](https://github.com/cowprotocol/cowswap/assets/70885163/41adf163-1a20-4bf9-9e0f-3478534e616c)

**Comment by elena-zh** [comment] 2024-01-24 09:16
Duplicate of #195

**Closed** 2024-06-27 13:57 UTC
Labels: app:CowSwap, Enhancement, Low
