### ISSUE TITLE
[iOS] - enable Feedback modal in imToken integrated browser

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/cowswap#165] opened 2022-04-02 22:08 UTC
**Description**
Feedback modals are currently disabled imToken integrated browser in iOS

**Expected behavior**
Enable feedback and NPS modals there

**Comment by elena-zh** [comment] 2022-06-29 14:48
> In Android the modal is opened in a wallet integrated browser, however, it is impossible to close it, so a user needs to reload the page ![image](https://user-images.githubusercontent.com/70885163/175001310-37332c0e-1955-4f39-ad91-290be42a4884.png)

This part is fixed in #753

**Comment by elena-zh** [comment] 2022-06-29 14:48
I have changed the issue priority and updated description due to the issue is relevant for 2 wallets in iOS only (MM and imToken)

**Comment by elena-zh** [comment] 2022-08-04 10:41
The issue is also reproducible for new NPS modal (#860 )

**Closed** 2024-06-27 13:56 UTC
Labels: app:CowSwap, Enhancement, Low
