### ISSUE TITLE
[1.48.0] WC doesn't disconnect

### ISSUE THREAD

**Issue by alfetopito** [cowprotocol/cowswap#3209] opened 2023-10-12 10:34 UTC
**Description**
WC v2 doesn't want to disconnect, so I can't re-connect it with a new wallet.

**How to Reproduce**
1. Connect using WC v2
2. Disconnect
3. Try to connect again
4. Nothing happens
5. Try to connect again
6. Modal hangs
7. Refresh the page
8. WC is connected again
9. Repeat 1 - 8
10. Same thing

**Expected behavior**
1. When I ask to disconnect, the connection is really gone
2. When I try to connect again, I'm able to

**Screenshots**

https://github.com/cowprotocol/cowswap/assets/43217/1862cdbc-c865-4557-96fa-663b45c248ed

**Additional context**
While testing release 1.48.0 https://github.com/cowprotocol/cowswap/pull/3203

**Comment by alfetopito** [comment] 2023-10-12 14:41
Not always able to reproduce it.

**Comment by elena-zh** [comment] 2023-12-01 14:37
One more issue with disconnect feature: CoW Swap does not show disconnected state when close connection from the wallet. To reproduce: 
1. Connect to a wallet using WC
2. Open a connected wallet, disconnect CoW Swap from there
3. Check the CoW Swap app --> it still shows connection. However, should be disconnected.

**Comment by anxolin** [comment] 2023-12-20 16:03
I also faced this one. The problem is that my WC stopped working (my wallet stopped receiving messages). So i said, ok I will disconnect and connect again. But I can.

This can block the user, so raising this to medium prio.

**Comment by elena-zh** [comment] 2024-05-23 11:09
Looks like is fixed in #4420

**Closed by elena-zh** 2024-05-23 11:09 UTC
Labels: Bug, Medium, RELEASE, Wallets
